name: Selenium Tests

on:
    push:
        branches: [04_03]
    pull_requests:
        branches: [04_03]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Install Chrome
              run: ./setup.sh

            - name: Run Tests
              run: mvn test
